version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - gradle build
  post_build:
    commands:
      - echo Build completed on `date`
     
artifacts:
    files: imagedefinitions.json
